

# https://github.com/flutter/plugins/blob/master/.travis.yml
matrix:
  include:
    # Job 1) Run tests
      - os:
        - linux
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - flutter test
      cache:
        directories:
          - $HOME/.pub-cache
    # Job 2) Build example APK
      - os: linux
        language: android
        licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
        android:
          components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-26
          - sys-img-armeabi-v7a-google_apis-26
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
        jdk: oraclejdk8
        sudo: true
        addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - libstdc++6
            - fonts-droid
        before_install:
        - yes | sdkmanager "platforms;android-27"
        before_script:
        - wget http://services.gradle.org/distributions/gradle-4.6-bin.zip
        - unzip -qq gradle-4.6-bin.zip
        - export GRADLE_HOME=$PWD/gradle-4.6
        - export PATH=$GRADLE_HOME/bin:$PATH
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        script:
        - flutter -v build apk
    # Job 3) Build IPA
    - os: osx
      env:
        - SHARD=Build-example-IPAs
      language: generic
      osx_image: xcode9.2
      before_script:
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - pod repo update
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate flutter_plugin_tools
      script:
        - flutter -v build ios

cache:
  directories:
    - $HOME/.pub-cache