matrix:
  include:
# Job 1 - run tests
  - os: linux
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libstdc++6
          - fonts-droid
    before_script:
      - git clone https://github.com/flutter/flutter.git
      - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
      - flutter doctor
    script:
      - flutter test
# Job 2 - build APK
  - os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-27.0.3
      - android-26
      - sys-img-armeabi-v7a-google_apis-26
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: true
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_install:
    - yes | sdkmanager "platforms;android-27"
    before_script:
    - wget http://services.gradle.org/distributions/gradle-4.6-bin.zip
    - unzip -qq gradle-4.6-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.6
    - export PATH=$GRADLE_HOME/bin:$PATH
    - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
    - ./flutter/bin/flutter doctor
    script:
    - ./flutter/bin/flutter -v build apk
cache:
  directories:
  - "$HOME/.pub-cache"
