name: calculator
description: A Calculator build with Google's Flutter.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_launcher_icons: ^0.2.0
  parsers: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_staggered_grid_view: ^0.1.2

flutter_icons:
  image_path: "icon/launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
