name: calculator
description: A simple calculator written in dart.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_staggered_grid_view: ^0.1.2
  parsers: "^1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true